### ISSUE TITLE
Can I use it in my rails4 project?

### ISSUE THREAD

**Issue by gaoguoxin** [phatworx/easy_captcha#20]
I want to use it in my rails4 project,but I received an error about empty error:
```ruby
Started GET "/captcha?i=1421717119" for ::1 at 2015-01-20 09:25:20 +0800

NoMethodError (undefined method `empty?' for nil:NilClass):
  actionview (4.2.0.rc2) lib/action_view/lookup_context.rb:176:in `normalize_name'
  actionview (4.2.0.rc2) lib/action_view/lookup_context.rb:151:in `args_for_lookup'
  actionview (4.2.0.rc2) lib/action_view/lookup_context.rb:130:in `exists?'
  actionview (4.2.0.rc2) lib/action_view/view_paths.rb:13:in `template_exists?'
  actionpack (4.2.0.rc2) lib/action_controller/metal/implicit_render.rb:14:in `method_for_action'
  actionpack (4.2.0.rc2) lib/abstract_controller/base.rb:230:in `_find_action_name'
  actionpack (4.2.0.rc2) lib/abstract_controller/base.rb:131:in `process'
  actionview (4.2.0.rc2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0.rc2) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0.rc2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0.rc2) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0.rc2) lib/action_controller/metal.rb:226:in `call'
  actionpack (4.2.0.rc2) lib/action_controller/metal.rb:226:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0.rc2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0.rc2) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack-mobile-detect (0.4.0) lib/rack/mobile-detect.rb:164:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0.rc2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0.rc2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0.rc2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0.rc2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0.rc2) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0.rc2) lib/rails/engine.rb:518:in `call'
  railties (4.2.0.rc2) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'

```

**Comment by bluefishers** [comment]
I encounter the same issue. Did you find the solution?

**Comment by SanderMander** [comment]
I have encountered with same problem after upgrading from rails 4.1.7 to 4.2. On rails 4.1.7 all was ok.

**Comment by SanderMander** [comment]
I've fixed issue and created pull request https://github.com/phatworx/easy_captcha/pull/21

**Comment by traxanos** [comment]
merged
